; PlatformIO Project Configuration File
;
; RF.Guru LoRa868Stick - LoRa 868 MHz Communication Stick
; RP2040 with USB Mass Storage for config
; Companion transmitter for 8PswitchLORA

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
board_build.filesystem = fatfs
board_build.arduino.earlephilhower.usb_manufacturer = RF.Guru
board_build.arduino.earlephilhower.usb_product = LoRa868Stick
board_build.arduino.earlephilhower.usb_vid = 0x1209
board_build.arduino.earlephilhower.usb_pid = 0xFF42
board_build.filesystem_size = 0.5m
monitor_speed = 115200
monitor_raw = yes
lib_deps =
    sandeepmistry/LoRa
    rweather/Crypto
